version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    enviromment:
      RABBITMQ_DEFAULT_USER: "packt"
      RABBITMQ_DEFAULT_PASS: "publishing"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq    
  redis:
    image: "redis:alpine"
    networks:
      - internal
    ports:
      - "6379:6379"
      
  redisCommander:
    image: tenstartups/redis-commander
    commander: --redis-host redis
    depends_on:
      - redis
    networks:
      - internal 
    ports:
      - "8081:8081"  
      
networks:
  internal:      